### ISSUE TITLE
Model has wrong count when it has been changed

### ISSUE THREAD

**Issue by paiext** [pureqml/qmlcore#180]
The count property of the model in the below example has 0 right after 'onModelChanged 'is fired even though it is assigned with three elements. It has 3 right after 'onCompleted'is fired.

```
[app.qml]
Item {  
  TestModel {
    model: ListModel {
      ListElement {
        color: 'red';
      }
      ListElement {
        color: 'green';
      }    
      ListElement {
        color: 'blue';
      }        
    }   
  }
}

[TestModel.qml]
Rectangle {
  property Object model;  
  
  onModelChanged: {    
    log('onModelChanged count: ' + this.model.count);
  }
  
  onCompleted: {
    log('onCompleted count: ' + this.model.count);
  }  
}
```
[test-model.zip](https://github.com/pureqml/qmlcore/files/4163196/test-model.zip)

**Comment by whoozle** [comment]
Just for the clarity, do you see the same thing?
```
qml.bug.js:2883 onModelChanged count: 0
qml.bug.js:3017 Context: created instance
qml.bug.js:2977 Context: signalling layout
qml.bug.js:2980 Context: calling completed()
qml.bug.js:2880 onCompleted count: 3
```

**Comment by whoozle** [comment]
Hi, I'm really pleased that you keep playing with pretty advanced topics of PureQML. 

First of all, the behaviour above is correct and intentional. Let me explain in detail.

Normally one could have very different relationships between objects. It could be arranged in cycles, all sort of backlinks from parent to child or siblings. 

We create objects in different phases to accomodate any cycles and any possible hierarchy. 

First phase is creating instances and registering them 
1. constructor
2. setting ids in local id contexts (propagating ids to the top)
3. addChild

No dynamic updates happens at the first phase, except `onChanged` for object holding properties like you have in your example onModelChanged. This triggers just after empty model has been assigned to property. 
It is because at any point of this stage you can't really say if any object you need has actually been constructed. 

Second phase: setting up all dynamic non-object properties, changed and signal handlers. 
We can say we constructed *each* object by the end of the previous phase, any object required by any property update or handler is now available. That's why you can write something like `testModel.onCountChanged: { … }` in any object which is more flexible than original QML. 


By the end of this phase, dynamic properties are set up, all values are set as well and importantly for the models, models data is populated by the end of this phase too. Model assingment is special too (more efficient than  `ListElement` + `addChild` combo)

```
_this_child0$model.assign([{"color": "red"}, {"color": "green"}, {"color": "blue"}])
```

The last phase: `onComplete` handlers. `onComplete` is special and it's handled a bit differently to achieve maximum performance (we think that our startup times are minimal comparing to other technologies)

So basically there's just a few guaranteed things you may have:
1. All object created and registered with their names (ids) before any dynamic values updated.
1b. Models are populated after all objects created, along with other dynamic properties. 
2. Delegates and views are not created until requested, normally there's no delegates until first tick() called
3. onCompleted called after all objects are ready to go, but exact order of onCompleted callbacks is unspecified. 

There's a few a few more guaranteed things, like `onVisibleInViewChanged/onRecursiveVisibleChanged` is called called with true when delegate appears and disappears. 

Regarding your example:
`onModelChanged` happened in phase 1, before model.assign([]) called. Our callbacks are always consistent, regardless of order as long as your values declared as `value: <expression>` form. 

Instead of using onModelChanged, you can declare onCountChanged within model, or use onCompleted, it should be always consistent. And again you don't have onCountChanged in prototype, you may declare it as `testMode.onCountChanged: { }` if you want. 

If you need any more details, feel free to ask

**Comment by paiext** [comment]
@whoozle 

Thank you for describing in detail!

Yes, I see the same thing.

So this is PureQML's own characteristic. That is a nice feature. I think this should be mentioned as a separate section in the website.

This subject seems to be about a trade-off between performance and intuition. When I first encountered this issue, it looked just like a defect. So I think it would be better if there was an option for the user to choose it. Or after changed, something like 'onModelAssigned'?

Less intuitive, less popular :) Generally popularity should be prioritized, of course, but I can't judge it.
