### ISSUE TITLE
Integrate video.jsmpeg for MUX livestreaming

### ISSUE THREAD

**Issue by maxiannunziata** [pureqml/qmlcore#198]
Hi All,

I try integrate the plugin video.jsmpeg for add mux.com live videostreaming service.

I put the require in .manifest file

`	"name": "pureosd",
	"platforms": ["web", "webos", "tizen", "netcast", "orsay", "androidtv"],
	"requires": ["video.jsmpeg"],
	"properties": {
		"title": "pureosd",`

Next: in my videoplayer block add the backend URL:

`    VideoPlayer {
            id: theBanner;
            width: 1920 s;
           height: "850";
    z: 1;
	backend: "https://stream.mux.com/iSfX7XBMQ9Az01sA01ikbKe01WYim5WysBe4EzkgKYP01gs.m3u8";
	autoPlay: false;
	backgroundImage: "res/vod/posters/theback.png";
}`

When i compile the code, the debug chrome response is:

`preferred backend: 
qml.app.js:4772 preferred backend: https://stream.mux.com/iSfX7XBMQ9Az01sA01ikbKe01WYim5WysBe4EzkgKYP01gs.m3u8
qml.app.js:728 on top changed callback failed:  TypeError: Cannot read property '0' of undefined
    at $core.Anchors.<anonymous> (qml.app.js:9373)
    at safeCallImpl (qml.app.js:388)
    at qml.app.js:392
    at Array.forEach (<anonymous>)
    at _callOnChanged (qml.app.js:731)
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.callOnChanged (qml.app.js:738)
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.set (qml.app.js:717)
    at $core.Anchors.simpleSet [as top] (qml.app.js:828)
    at $src.HeaderDelegate.HeaderDelegatePrototype.$s (qml.app.js:3644)`

[iSfX7XBMQ9Az01sA01ikbKe01WYim5WysBe4EzkgKYP01gs (2).m3u8.txt](https://github.com/pureqml/qmlcore/files/6331450/iSfX7XBMQ9Az01sA01ikbKe01WYim5WysBe4EzkgKYP01gs.2.m3u8.txt)

what am I doing wrong?

**Comment by comrat** [comment]
Hello!
If you want to use another video player backend you should implement it first and place it in a separate directory (i.e. qmlcore/platform/video.jsmpeg`). You must implement PureQML VideoPlayer API there then you can add it in the `required section in the app manifest.
The second thing: you should pass a video URL to the source property instead of backend: VideoPlayer { source: "https://stream.mux.com/iSfX7XBMQ9Az01sA01ikbKe01WYim5WysBe4EzkgKYP01gs.m3u8"; }
