### ISSUE TITLE
qmlweb vs pureqml

### ISSUE THREAD

**Issue by seniorivn** [pureqml/qmlcore#36]
[QMLWEB project aims at bringing the power of QML to the web browser. Here's a sample of how QML looks like:](https://github.com/qmlweb/qmlweb
)
any comments or compression of this two projects?

**Comment by vkrv** [comment]
Vadim Kravchenko:
We knew about qmlweb when we started this one. For the purpose of our project, at that time, qmlweb was an obvious option, and we've tried to stick with it. But soon we found it doesn't fit well to our needs and 
having significant prior experience with QML we've seen whole approach in a different way. That's why we started pureqml. The core differences​:
- we do QML parsing/translation/generation ahead of time. It gives more flexibility for optimization and maintenance and ease components creation;
- we are not focused strictly on web and while web is most comprehensive, platform abstraction allow to adopt pureqml to a number of Smart TVs easily;
- with all the respect to qmlweb guys (I actually love what they are doing), some parts of pureqml a more mature even the project is younger;
- we are using pureqml in our commercial projects, not a big deal, but it means we won't give up on maintenance suddenly.

For sure, there are a lot of other differences, I mentioned only what we consider important.
